// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package org.marouanedbibih.grpc.stubs;

public final class CompteOuterClass {
  private CompteOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Compte_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Compte_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CompteREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CompteREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SoldeStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SoldeStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllComptesREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllComptesREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllComptesRES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllComptesRES_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCompteByIdREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCompteByIdREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetCompteByIdRES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetCompteByIdRES_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTotalSoldeREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTotalSoldeREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTotalSoldeRES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTotalSoldeRES_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveCompteREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveCompteREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SaveCompteRES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SaveCompteRES_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateCompteREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateCompteREQ_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateCompteRES_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateCompteRES_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteCompteREQ_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteCompteREQ_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014compte.proto\032\033google/protobuf/empty.pr" +
      "oto\"T\n\006Compte\022\n\n\002id\030\001 \001(\003\022\r\n\005solde\030\002 \001(\002" +
      "\022\024\n\014dateCreation\030\003 \001(\t\022\031\n\004type\030\004 \001(\0162\013.T" +
      "ypeCompte\"K\n\tCompteREQ\022\r\n\005solde\030\001 \001(\002\022\024\n" +
      "\014dateCreation\030\002 \001(\t\022\031\n\004type\030\003 \001(\0162\013.Type" +
      "Compte\"9\n\nSoldeStats\022\r\n\005count\030\001 \001(\005\022\013\n\003s" +
      "um\030\002 \001(\002\022\017\n\007average\030\003 \001(\002\"\022\n\020GetAllCompt" +
      "esREQ\",\n\020GetAllComptesRES\022\030\n\007comptes\030\001 \003" +
      "(\0132\007.Compte\"\036\n\020GetCompteByIdREQ\022\n\n\002id\030\001 " +
      "\001(\003\"+\n\020GetCompteByIdRES\022\027\n\006compte\030\001 \001(\0132" +
      "\007.Compte\"\022\n\020GetTotalSoldeREQ\".\n\020GetTotal" +
      "SoldeRES\022\032\n\005stats\030\001 \001(\0132\013.SoldeStats\"+\n\r" +
      "SaveCompteREQ\022\032\n\006compte\030\001 \001(\0132\n.CompteRE" +
      "Q\"(\n\rSaveCompteRES\022\027\n\006compte\030\001 \001(\0132\007.Com" +
      "pte\"*\n\017UpdateCompteREQ\022\027\n\006compte\030\001 \001(\0132\007" +
      ".Compte\"6\n\017UpdateCompteRES\022\n\n\002id\030\001 \001(\003\022\027" +
      "\n\006compte\030\002 \001(\0132\007.Compte\"\035\n\017DeleteCompteR" +
      "EQ\022\n\n\002id\030\001 \001(\003*&\n\nTypeCompte\022\013\n\007COURANT\020" +
      "\000\022\013\n\007EPARGNE\020\0012\307\002\n\rCompteService\0222\n\nAllC" +
      "omptes\022\021.GetAllComptesREQ\032\021.GetAllCompte" +
      "sRES\0222\n\nCompteById\022\021.GetCompteByIdREQ\032\021." +
      "GetCompteByIdRES\0222\n\nTotalSolde\022\021.GetTota" +
      "lSoldeREQ\032\021.GetTotalSoldeRES\022,\n\nSaveComp" +
      "te\022\016.SaveCompteREQ\032\016.SaveCompteRES\0222\n\014Up" +
      "dateCompte\022\020.UpdateCompteREQ\032\020.UpdateCom" +
      "pteRES\0228\n\014DeleteCompte\022\020.DeleteCompteREQ" +
      "\032\026.google.protobuf.EmptyB!\n\035org.marouane" +
      "dbibih.grpc.stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_Compte_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Compte_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Compte_descriptor,
        new java.lang.String[] { "Id", "Solde", "DateCreation", "Type", });
    internal_static_CompteREQ_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CompteREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CompteREQ_descriptor,
        new java.lang.String[] { "Solde", "DateCreation", "Type", });
    internal_static_SoldeStats_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SoldeStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SoldeStats_descriptor,
        new java.lang.String[] { "Count", "Sum", "Average", });
    internal_static_GetAllComptesREQ_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetAllComptesREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllComptesREQ_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllComptesRES_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetAllComptesRES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllComptesRES_descriptor,
        new java.lang.String[] { "Comptes", });
    internal_static_GetCompteByIdREQ_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetCompteByIdREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCompteByIdREQ_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetCompteByIdRES_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetCompteByIdRES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetCompteByIdRES_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_GetTotalSoldeREQ_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GetTotalSoldeREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTotalSoldeREQ_descriptor,
        new java.lang.String[] { });
    internal_static_GetTotalSoldeRES_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_GetTotalSoldeRES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTotalSoldeRES_descriptor,
        new java.lang.String[] { "Stats", });
    internal_static_SaveCompteREQ_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_SaveCompteREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveCompteREQ_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_SaveCompteRES_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_SaveCompteRES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SaveCompteRES_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_UpdateCompteREQ_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_UpdateCompteREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateCompteREQ_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_UpdateCompteRES_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_UpdateCompteRES_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateCompteRES_descriptor,
        new java.lang.String[] { "Id", "Compte", });
    internal_static_DeleteCompteREQ_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_DeleteCompteREQ_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteCompteREQ_descriptor,
        new java.lang.String[] { "Id", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
