// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package org.marouanedbibih.grpc.stubs;

public interface GetAllComptesREQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllComptesREQ)
    com.google.protobuf.MessageOrBuilder {
}
