// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package org.marouanedbibih.grpc.stubs;

public interface GetAllComptesRESOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllComptesRES)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<org.marouanedbibih.grpc.stubs.Compte> 
      getComptesList();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  org.marouanedbibih.grpc.stubs.Compte getComptes(int index);
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  int getComptesCount();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<? extends org.marouanedbibih.grpc.stubs.CompteOrBuilder> 
      getComptesOrBuilderList();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  org.marouanedbibih.grpc.stubs.CompteOrBuilder getComptesOrBuilder(
      int index);
}
