// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package org.marouanedbibih.grpc.stubs;

public interface GetTotalSoldeREQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTotalSoldeREQ)
    com.google.protobuf.MessageOrBuilder {
}
