// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package org.marouanedbibih.grpc.stubs;

/**
 * <pre>
 * Réponse contenant les statistiques de solde
 * </pre>
 *
 * Protobuf type {@code GetTotalSoldeRES}
 */
public  final class GetTotalSoldeRES extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetTotalSoldeRES)
    GetTotalSoldeRESOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTotalSoldeRES.newBuilder() to construct.
  private GetTotalSoldeRES(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTotalSoldeRES() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTotalSoldeRES();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTotalSoldeRES(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.marouanedbibih.grpc.stubs.SoldeStats.Builder subBuilder = null;
            if (stats_ != null) {
              subBuilder = stats_.toBuilder();
            }
            stats_ = input.readMessage(org.marouanedbibih.grpc.stubs.SoldeStats.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(stats_);
              stats_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.marouanedbibih.grpc.stubs.CompteOuterClass.internal_static_GetTotalSoldeRES_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.marouanedbibih.grpc.stubs.CompteOuterClass.internal_static_GetTotalSoldeRES_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.marouanedbibih.grpc.stubs.GetTotalSoldeRES.class, org.marouanedbibih.grpc.stubs.GetTotalSoldeRES.Builder.class);
  }

  public static final int STATS_FIELD_NUMBER = 1;
  private org.marouanedbibih.grpc.stubs.SoldeStats stats_;
  /**
   * <code>.SoldeStats stats = 1;</code>
   * @return Whether the stats field is set.
   */
  public boolean hasStats() {
    return stats_ != null;
  }
  /**
   * <code>.SoldeStats stats = 1;</code>
   * @return The stats.
   */
  public org.marouanedbibih.grpc.stubs.SoldeStats getStats() {
    return stats_ == null ? org.marouanedbibih.grpc.stubs.SoldeStats.getDefaultInstance() : stats_;
  }
  /**
   * <code>.SoldeStats stats = 1;</code>
   */
  public org.marouanedbibih.grpc.stubs.SoldeStatsOrBuilder getStatsOrBuilder() {
    return getStats();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stats_ != null) {
      output.writeMessage(1, getStats());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (stats_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStats());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.marouanedbibih.grpc.stubs.GetTotalSoldeRES)) {
      return super.equals(obj);
    }
    org.marouanedbibih.grpc.stubs.GetTotalSoldeRES other = (org.marouanedbibih.grpc.stubs.GetTotalSoldeRES) obj;

    if (hasStats() != other.hasStats()) return false;
    if (hasStats()) {
      if (!getStats()
          .equals(other.getStats())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStats()) {
      hash = (37 * hash) + STATS_FIELD_NUMBER;
      hash = (53 * hash) + getStats().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.marouanedbibih.grpc.stubs.GetTotalSoldeRES prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Réponse contenant les statistiques de solde
   * </pre>
   *
   * Protobuf type {@code GetTotalSoldeRES}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetTotalSoldeRES)
      org.marouanedbibih.grpc.stubs.GetTotalSoldeRESOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.marouanedbibih.grpc.stubs.CompteOuterClass.internal_static_GetTotalSoldeRES_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.marouanedbibih.grpc.stubs.CompteOuterClass.internal_static_GetTotalSoldeRES_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.marouanedbibih.grpc.stubs.GetTotalSoldeRES.class, org.marouanedbibih.grpc.stubs.GetTotalSoldeRES.Builder.class);
    }

    // Construct using org.marouanedbibih.grpc.stubs.GetTotalSoldeRES.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statsBuilder_ == null) {
        stats_ = null;
      } else {
        stats_ = null;
        statsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.marouanedbibih.grpc.stubs.CompteOuterClass.internal_static_GetTotalSoldeRES_descriptor;
    }

    @java.lang.Override
    public org.marouanedbibih.grpc.stubs.GetTotalSoldeRES getDefaultInstanceForType() {
      return org.marouanedbibih.grpc.stubs.GetTotalSoldeRES.getDefaultInstance();
    }

    @java.lang.Override
    public org.marouanedbibih.grpc.stubs.GetTotalSoldeRES build() {
      org.marouanedbibih.grpc.stubs.GetTotalSoldeRES result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.marouanedbibih.grpc.stubs.GetTotalSoldeRES buildPartial() {
      org.marouanedbibih.grpc.stubs.GetTotalSoldeRES result = new org.marouanedbibih.grpc.stubs.GetTotalSoldeRES(this);
      if (statsBuilder_ == null) {
        result.stats_ = stats_;
      } else {
        result.stats_ = statsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.marouanedbibih.grpc.stubs.GetTotalSoldeRES) {
        return mergeFrom((org.marouanedbibih.grpc.stubs.GetTotalSoldeRES)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.marouanedbibih.grpc.stubs.GetTotalSoldeRES other) {
      if (other == org.marouanedbibih.grpc.stubs.GetTotalSoldeRES.getDefaultInstance()) return this;
      if (other.hasStats()) {
        mergeStats(other.getStats());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.marouanedbibih.grpc.stubs.GetTotalSoldeRES parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.marouanedbibih.grpc.stubs.GetTotalSoldeRES) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.marouanedbibih.grpc.stubs.SoldeStats stats_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.marouanedbibih.grpc.stubs.SoldeStats, org.marouanedbibih.grpc.stubs.SoldeStats.Builder, org.marouanedbibih.grpc.stubs.SoldeStatsOrBuilder> statsBuilder_;
    /**
     * <code>.SoldeStats stats = 1;</code>
     * @return Whether the stats field is set.
     */
    public boolean hasStats() {
      return statsBuilder_ != null || stats_ != null;
    }
    /**
     * <code>.SoldeStats stats = 1;</code>
     * @return The stats.
     */
    public org.marouanedbibih.grpc.stubs.SoldeStats getStats() {
      if (statsBuilder_ == null) {
        return stats_ == null ? org.marouanedbibih.grpc.stubs.SoldeStats.getDefaultInstance() : stats_;
      } else {
        return statsBuilder_.getMessage();
      }
    }
    /**
     * <code>.SoldeStats stats = 1;</code>
     */
    public Builder setStats(org.marouanedbibih.grpc.stubs.SoldeStats value) {
      if (statsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stats_ = value;
        onChanged();
      } else {
        statsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.SoldeStats stats = 1;</code>
     */
    public Builder setStats(
        org.marouanedbibih.grpc.stubs.SoldeStats.Builder builderForValue) {
      if (statsBuilder_ == null) {
        stats_ = builderForValue.build();
        onChanged();
      } else {
        statsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.SoldeStats stats = 1;</code>
     */
    public Builder mergeStats(org.marouanedbibih.grpc.stubs.SoldeStats value) {
      if (statsBuilder_ == null) {
        if (stats_ != null) {
          stats_ =
            org.marouanedbibih.grpc.stubs.SoldeStats.newBuilder(stats_).mergeFrom(value).buildPartial();
        } else {
          stats_ = value;
        }
        onChanged();
      } else {
        statsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.SoldeStats stats = 1;</code>
     */
    public Builder clearStats() {
      if (statsBuilder_ == null) {
        stats_ = null;
        onChanged();
      } else {
        stats_ = null;
        statsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.SoldeStats stats = 1;</code>
     */
    public org.marouanedbibih.grpc.stubs.SoldeStats.Builder getStatsBuilder() {
      
      onChanged();
      return getStatsFieldBuilder().getBuilder();
    }
    /**
     * <code>.SoldeStats stats = 1;</code>
     */
    public org.marouanedbibih.grpc.stubs.SoldeStatsOrBuilder getStatsOrBuilder() {
      if (statsBuilder_ != null) {
        return statsBuilder_.getMessageOrBuilder();
      } else {
        return stats_ == null ?
            org.marouanedbibih.grpc.stubs.SoldeStats.getDefaultInstance() : stats_;
      }
    }
    /**
     * <code>.SoldeStats stats = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.marouanedbibih.grpc.stubs.SoldeStats, org.marouanedbibih.grpc.stubs.SoldeStats.Builder, org.marouanedbibih.grpc.stubs.SoldeStatsOrBuilder> 
        getStatsFieldBuilder() {
      if (statsBuilder_ == null) {
        statsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.marouanedbibih.grpc.stubs.SoldeStats, org.marouanedbibih.grpc.stubs.SoldeStats.Builder, org.marouanedbibih.grpc.stubs.SoldeStatsOrBuilder>(
                getStats(),
                getParentForChildren(),
                isClean());
        stats_ = null;
      }
      return statsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetTotalSoldeRES)
  }

  // @@protoc_insertion_point(class_scope:GetTotalSoldeRES)
  private static final org.marouanedbibih.grpc.stubs.GetTotalSoldeRES DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.marouanedbibih.grpc.stubs.GetTotalSoldeRES();
  }

  public static org.marouanedbibih.grpc.stubs.GetTotalSoldeRES getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTotalSoldeRES>
      PARSER = new com.google.protobuf.AbstractParser<GetTotalSoldeRES>() {
    @java.lang.Override
    public GetTotalSoldeRES parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTotalSoldeRES(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTotalSoldeRES> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTotalSoldeRES> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.marouanedbibih.grpc.stubs.GetTotalSoldeRES getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

