// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package org.marouanedbibih.grpc.stubs;

public interface SaveCompteREQOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveCompteREQ)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CompteREQ compte = 1;</code>
   * @return Whether the compte field is set.
   */
  boolean hasCompte();
  /**
   * <code>.CompteREQ compte = 1;</code>
   * @return The compte.
   */
  org.marouanedbibih.grpc.stubs.CompteREQ getCompte();
  /**
   * <code>.CompteREQ compte = 1;</code>
   */
  org.marouanedbibih.grpc.stubs.CompteREQOrBuilder getCompteOrBuilder();
}
