// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package org.marouanedbibih.grpc.stubs;

public interface UpdateCompteRESOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateCompteRES)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.Compte compte = 2;</code>
   * @return Whether the compte field is set.
   */
  boolean hasCompte();
  /**
   * <code>.Compte compte = 2;</code>
   * @return The compte.
   */
  org.marouanedbibih.grpc.stubs.Compte getCompte();
  /**
   * <code>.Compte compte = 2;</code>
   */
  org.marouanedbibih.grpc.stubs.CompteOrBuilder getCompteOrBuilder();
}
